trigger:
- '*'

pr:
- '*'

jobs:
- job: Linux

  pool: 'AWS'

  steps:

  - script: |
      source /localdisk/miniconda3/bin/activate
      conda activate dpcomp_build_env
      conda list
      export LLVM_PATH=/localdisk/llvm/mlir-llvm_latest_Linux
      export TBB_PATH=/localdisk/tbb
      sed -i 's/add_subdirectory(tools)/# add_subdirectory(tools)/g' CMakeLists.txt
      sed -i 's/from dpnp import get_include as dpnp_get_include/raise ImportError/g' setup.py
      python setup.py develop
    displayName: 'Build'

  - script: |
      source /localdisk/miniconda3/bin/activate
      conda activate dpcomp_build_env
      conda list
      source /localdisk/tbb/env/vars.sh
      python -c "import numba; print('numba', numba.__version__)"
      pytest -vv --capture=tee-sys
    displayName: 'Tests'
