builtin.module(
    cse
    gpu.module(xetile-init-duplicate
        xetile-canonicalization
        xetile-blockop-fallback
        xetile-blocking
	cse
        convert-xetile-to-xegpu
	cse
        imex-xegpu-hoist-transpose
        imex-xegpu-apply-vnni-transformation
        imex-xegpu-optimize-transpose
        cse
        convert-xegpu-to-vc)
    cse
    imex-vector-linearize
    canonicalize
    cse
    reconcile-unrealized-casts
    bf16-to-gpu
    cse
    imex-convert-gpu-to-spirv
    spirv.module(spirv-lower-abi-attrs
             spirv-update-vce)
    func.func(llvm-request-c-wrappers)
    serialize-spirv
    convert-vector-to-scf
    convert-gpu-to-gpux
    convert-scf-to-cf
    expand-strided-metadata
    finalize-memref-to-llvm
    convert-cf-to-llvm
    convert-vector-to-llvm
    convert-index-to-llvm
    convert-arith-to-llvm
    convert-func-to-llvm
    convert-math-to-llvm
    convert-gpux-to-llvm
    lower-affine
    reconcile-unrealized-casts)
